server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://personas-aws-personas.c12eoeiwy86w.us-east-2.rds.amazonaws.com:5432/personas_db
    username: postgres
    password: Induccion2025+
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
