server:
  port: 8080

spring:
  datasource:
    #url: ${/dev/db-url}
    #username: ${/dev/db-credentials.db_username}
    #password: ${/dev/db-credentials.db_password}
    #driver-class-name: org.postgresql.Driver

    #url: ${SPRING_DATASOURCE_URL}
    #username: ${SPRING_DATASOURCE_USERNAME}
    #password: ${SPRING_DATASOURCE_PASSWORD}

    url: jdbc:postgresql://${db_name}:5432/${db_database}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
